#Example of how to get current date into variable to use in playbook such as passing date to a command or naming file with current date
#Should work with all linux date formats - e.g. %Y - 4 digit year or %y for 2 digit year.
#Add separators to date as needed - e.g. %m-%d-%y will produce MM-DD-YY or %m/%d/%Y MM/DD/YYY
---
- name: date example
  hosts: localhost
  become: false
  gather_facts: yes
  vars:
    today: "{{ lookup('pipe', 'date +%Y%m%d') }}"

  tasks:
    - name: date
      debug:
        msg: "{{ today }}"
